Chore: Set up custom ESLint and Prettier configs
naomi-lgbt/denna pull request #855
Opened 2023-12-16 19:56 UTC by a2937

# Pull Request

## Description:

I followed all the steps but Eslint gave me some issues with path resolution and I wasn't sure if you wanted the console statement. 

## Related Issue:

Closes #848

2023-12-16 20:14 UTC, naomi-lgbt requested changes
`console.err(err)` can be replaced with `alert(err)`.

2023-12-16 20:14 UTC, naomi-lgbt commented on src/app/gallery/gallery.component.ts
> +import { FeaturedSimsInt } from "src/assets/interfaces/FeaturedSimsInt";
```suggestion
import { Component, OnInit } from "@angular/core";

import { featuredHouses, featuredRooms } from "../../assets/data/featured";
import { FeaturedSimsInt } from "../../assets/interfaces/FeaturedSimsInt";
```

Resolves the unresolved path error.

2023-12-16 20:14 UTC, naomi-lgbt commented on src/app/home/home.component.ts
> +import { introText } from "src/assets/data/intro";
```suggestion
import { Component, OnInit } from "@angular/core";

import { introText } from "../../assets/data/intro";
```

2023-12-16 21:02 UTC, naomi-lgbt requested changes
I think these should all be safe to remove. Didn't test locally tho.

(Dang this code is ancient)

2023-12-16 21:02 UTC, naomi-lgbt commented on src/app/app.component.spec.ts
>    let component: AppComponent;
```suggestion
```

2023-12-16 21:02 UTC, naomi-lgbt commented on src/app/footer/footer.component.spec.ts
>    beforeEach(() => {});
```suggestion
```

2023-12-16 21:02 UTC, naomi-lgbt commented on src/app/footer/footer.component.ts
> +  constructor() {}
```suggestion
```

2023-12-16 21:02 UTC, naomi-lgbt commented on src/app/gallery/gallery.component.spec.ts
>    beforeEach(() => {});
```suggestion
```

2023-12-16 21:02 UTC, naomi-lgbt commented on src/app/gallery/gallery.component.ts
>    constructor() {}
```suggestion
```

2023-12-16 21:02 UTC, naomi-lgbt commented on src/app/home/home.component.ts
>    constructor() {}
```suggestion
```

2023-12-16 21:02 UTC, naomi-lgbt commented on src/app/nav/nav.component.ts
> +  constructor() {}
```suggestion
```

2023-12-16 21:08 UTC, a2937 commented on src/app/app.component.spec.ts
>    let component: AppComponent;
Actually Naomi you assigned it a value. If you directly remove it like that, it'll break. But the test code seems to be in need of an update, which is out of scope for this PR.

2023-12-16 21:13 UTC, a2937 commented on src/app/app.component.spec.ts
>    let component: AppComponent;
Ideally I'd like to stay until a new PR gets made to redo the tests.

2023-12-16 23:45 UTC, naomi-lgbt commented on src/app/app.component.spec.ts
>    let component: AppComponent;
If the assigned value isn't used either, we can just... remove that too.

2023-12-17 01:45 UTC, a2937 commented on src/app/app.component.spec.ts
>    let component: AppComponent;
Okay done.

2023-12-17 04:37 UTC, naomi-lgbt commented on src/app/app.component.spec.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
```suggestion
```

2023-12-17 04:41 UTC, naomi-lgbt requested changes
Couple of the files need a prettier run again :3

2023-12-17 04:41 UTC, naomi-lgbt commented on src/app/app.component.spec.ts
>    let component: AppComponent;
Oh I see what happened here.

`component` needs to be removed - it's unused.
`compiled` needs to be put back, that one's actually used in the tests,

2023-12-17 13:05 UTC, a2937 commented on src/app/app.component.spec.ts
>    let component: AppComponent;
Just fixed.

2023-12-17 16:13 UTC, naomi-lgbt approved these changes

2023-12-17 16:13 UTC, merged